sudo: required
language: bash
services:
  - docker
before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
script:
  - archs=( armhf arm64 )
  - for arch in ${archs[@]}; do docker build --build-arg ARCH=${arch} --no-cache -t mfilipe/znc:${arch} .; done
  - docker push mfilipe/znc
